### ISSUE TITLE
Inssue with Better Combat on Quilt

### ISSUE THREAD

**Issue by Rozmun-Narseeker** [MoriyaShiine/enchancement#169]
### Mod version (NOT Minecraft version)

1.20-21

### A description of the issue

Striking when pointing at the hitbox of a mob triggers a vanilla hit, instead of strikes from Better Combat.
Minecraft 1.20.1
Quilt 0.24.0
Better Combat 1.8.4

### Log or crash report

No response

**Comment by MoriyaShiine** [comment]
This is probably caused by Coyote Bite, which allows entities to be hit for a couple ticks after the crosshair leaves the hitbox. I don't know much about Better Combat, would a good fix be to just disable Coyote Bite if Better Combat is installed? You can test how that would work by setting coyoteBiteTicks to 0 in the config

**Comment by majorsanty** [comment]
I can confirm, disabling coyoteBiteTicks fixes it.

**Comment by MoriyaShiine** [comment]
Cool, that's what I did in the commit :p
