### ISSUE TITLE
Shift and Ctrl don't work

### ISSUE THREAD

**Issue by Fcmns** [MoriyaShiine/enchancement#211]
### Confirmations

- [ ] I can verify that I am running the mod on the latest possible Minecraft version.
- [ ] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

v1.20-26

### A description of the issue

I was testing the modpack I created and find out, that with Enchancement enabled, Shift or Ctrl key didn't work, and, only the vanilla features of these buttons, which are shift and running, but features of other mods that were binded to these buttons works fine. Rebinding buttons also gives zero results. Buttons do work with Enchancement being disabled. I honestly don't know if it's problem of this mod or just some other mod conflicting with it
There's my mod list:
![mods 06 12 2024 15_04_14](https://github.com/user-attachments/assets/471d2b5f-b4ab-4f7b-b302-ab351a812a0d)
![mods 06 12 2024 15_04_09](https://github.com/user-attachments/assets/8c83dbc7-9edc-4af7-98d7-24ed1a15f191)

### Log or crash report

https://gist.github.com/Fcmns/29106970c8972b1cebb1c833a4106cfa

**Comment by MoriyaShiine** [comment]
It's an incompatibility with Balm, it returns false on if keybinds match if they match (interestingly) as seen in [this mixin](https://github.com/TwelveIterationMods/Balm/blob/1.21.4/common/src/main/java/net/blay09/mods/balm/mixin/KeyMappingMixin.java) and [this method](https://github.com/TwelveIterationMods/Balm/blob/1.21.4/common/src/main/java/net/blay09/mods/balm/common/client/keymappings/CommonBalmKeyMappings.java#L176), so Enchancement's code never has a chance to run (since it assumes that the matching keys match) because of Balm's unconditional inject at head if they do.

**Comment by NextRaven10** [comment]
A workaround for me is using [KeyBindFix](https://modrinth.com/mod/keybind-fix)
