### ISSUE TITLE
Conflict with the mod "Cobblemon"

### ISSUE THREAD

**Issue by deSpaceman** [MoriyaShiine/enchancement#219]
### Confirmations

- [ ] I can verify that I am running the mod on the latest possible Minecraft version.
- [ ] I can verify that the issue I am reporting exists on the latest possible Mod version.

### Mod version (NOT Minecraft version)

1.21-r14

### A description of the issue

Having Enchancement and Cobblemon (more specifically version 1.6.0) installed/enabled in the same instance results in the Poké Rod item becoming unable cast the line and the log being spammed with packet handling errors.

### Log or crash report

https://gist.github.com/deSpaceman/6c5fcf675339c34a1fb08cdec947cff3

**Comment by MoriyaShiine** [comment]
1.21.1 is no longer supported. This shouldn't be an issue in 1.21.4 and above due to some minor registry changes (I may be wrong but I'm fairly certain optional registry entries should never return empty now), but a band-aid solution would be to re-add Lure in the config, and optionally add it to the `enchancement:unselectable` enchantment tag to prevent it from showing up in the enchanting table.

**Comment by deSpaceman** [comment]
It worked, thank you
