### ISSUE TITLE
Create mod glue incompatibility

### ISSUE THREAD

**Issue by Vykonn** [MoriyaShiine/enchancement#67]
### Mod version

v1.18-18

### A description of the issue

Cannot use glue from [Create Fabric](https://modrinth.com/mod/create-fabric) in survival.

![2022-11-11_14 05 14](https://user-images.githubusercontent.com/79595583/201412719-6df2a642-7454-4281-8564-9a7355069aee.png)

The GUI just says "Not enough glue in inventory."
My guess at why this happens is that normally, durability would be taken away from the glue, until it has none left, and breaks.
However, due to it having no durability, Create assumes that there's not enough durability, and refuses to let it be used.
A fix would just be to enable durability for glue. I tried to do this with the item tags, but I couldn't figure out what tag enabled durability.

**Comment by deli73** [comment]
this is arguably just as much an issue with how Create checks for glue durability, but yeah we've encountered this as well

**Comment by GameOnne** [comment]
I've had this issue on my own. I later got help from the owner and you have to do it through a datapack.
Create the "data" folder. In there create folders as following: "enchancement", "tags", "items". In the "items" folder create a .json file named "retains_durability". Paste the following text into the .json file:
```
{
  "replace": false,
  "values": [
	"create:super_glue"
  ]
}
```
Now go back to the pack's core folder and create "pack.mcmeta" file. Paste the following:
```
{
  "pack": {
    "pack_format": X,
    "description": "Durability test"
  }
}
```
Instead of X you have to put a value that depends on your game's version. 10 for 1.19+, 9 for 1.18.2, 8 for 1.18-1.18.1, etc.
Put the pack into your world's datapacks folder, reload your datapacks if you're already in your world using /reload, and there you have it.
This pack is not mine, all credit goes to MoriyaShiine, enchancement's developer who sent me this pack. I later modified the pack to work with glue.

**Comment by deli73** [comment]
This datapack doesn't seem to fix things, we're still having the same issue on the server, even though the fix works in single player

**Comment by GameOnne** [comment]
Are you sure you've enabled the datapack? Use `/datapack list` to see all available datapacks. Use `/datapack enable [datapack]` to enable it if you haven't.

**Comment by deli73** [comment]
it's definitely active. we put it in another datapack that's still working, and we're not seeing any relevant errors...

**Comment by GameOnne** [comment]
Here's a datapack I use. It fixes the issue with glue on my friend's server. It's made for 1.19+ though. You can make it compatible with 1.18.2 and 1.18 by modifying `"pack_format"` in the pack.mcmeta file. 9 for 1.18.2, 8 for 1.18-1.18.1 (although I'm not sure if this is required for the datapack to work). Make sure to paste the folder inside (durabilitytest) into the datapack folder, not the .zip itself.
[create glue compatibility.zip](https://github.com/MoriyaShiine/enchancement/files/10230206/create.glue.compatibility.zip)
