### ISSUE TITLE
Version 1.19-12 crashes with Health Overlay

### ISSUE THREAD

**Issue by SplendidAlakey** [MoriyaShiine/enchancement#82]
### Mod version

1.19-12

### A description of the issue

When [Health Overlay](https://www.curseforge.com/minecraft/mc-mods/health-overlay-fabric) is installed together with the [newest version of Enchancement](https://www.curseforge.com/minecraft/mc-mods/enchancement/files/4398114), the game crashes on startup.

### Log or crash report

https://gist.github.com/SplendidAlakey/53da65381de6ef7b65585f359c59950c

**Comment by MoriyaShiine** [comment]
This is up to them to fix, they use an Overwrite which will break any mod that mixins into that method, even if it would otherwise be compatible

https://github.com/Terrails/HealthOverlay/blob/1.19.2/fabric/src/main/java/terrails/healthoverlay/fabric/mixin/GuiMixin.java#L24

See: https://mixin-wiki.readthedocs.io/overwriting-methods/
