### ISSUE TITLE
Enchancement Server Crash

### ISSUE THREAD

**Issue by DoctorDragosaur** [MoriyaShiine/enchancement#83]
### Mod version

1.19-13

### A description of the issue

Enchancement causes server to crash. I am not educated enough in java to fully understand why. I would like assistance on fixing this issue. 

### Log or crash report

https://gist.github.com/DoctorDragosaur/1e8a5a5c1ed168ad9c0df5179ac20d66

**Comment by MoriyaShiine** [comment]
I'm not sure why this is happening either, but it seems to be the server terminating itself because it took too long. It's happening during Buoy checks, try seeing if your server is doing anything intensive with entities on water? It may be another mod calling the method too frequently but I'm not sure

**Comment by DoctorDragosaur** [comment]
How do you do that?

**Comment by DoctorDragosaur** [comment]
> I'm not sure why this is happening either, but it seems to be the server terminating itself because it took too long. It's happening during Buoy checks, try seeing if your server is doing anything intensive with entities on water? It may be another mod calling the method too frequently but I'm not sure

I seem to have fixed it. Further testing is required. It was in fact the Fish of Thieves mod that was causing the crash.
